"options":
  "fqdns":
    "type": "string"
    "default": ""
    "description": |
      Space-separated list of domain names. These will share the same certificate.
  "credentials":
    "type": "string"
    "default": ""
    "description": |
      Space-separated username and password for basic authentication.
  "contact-email":
    "type": "string"
    "default": ""
    "description": |
      Contact email for Let's Encrypt
  "nginx-config":
    "type": "string"
    "default": ""
    "description": |
      ; separated list with NGINX configs. These options will be added to the location block. Ex. 'client_max_body_size 9G;client_body_timeout 50s;'
  "upstreams":
    "type": "string"
    "default": ""
    "description": |
      Space separated list with upstreams.
